---
title: "Class14.1"
author: "Kimberly"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read this file into R and determine the sample size for each genotype and their corresponding median expression levels for each of these genotypes.
```{r}
info <- read.table("rs8067378_ENSG00000172057.6.txt")
info

head(info)
```

Extract the A/A rows (i.e., where the $geno is equal to "A/A").
```{r}
indices_A <- info$geno == "A/A"
indices_A
```

Get the expression of those in the A/A rows.
```{r}
# looking at the elements that are 'True' and outputting such rows
info[indices_A, ]

# gives you just the expression values
info[indices_A, ]$exp

summary(info[indices_A, ]$exp)
```

Extract the G/G rows (i.e., where the $geno is equal to "G/G").
```{r}
indices_G <- info$geno == "G/G"
indices_G

# looking at the elements that are 'True' and outputting such rows
info[indices_G, ]

summary(info[indices_G, ]$exp)
```

Box plot for comparisons of **expressions (exp)** between A/A and G/G and A/G.
```{r}
boxplot(exp ~ geno, data = info, notch = T)
# if notches don't overlap, usually good for statistical significance
```

